module.exports = {
    'USER_NOT_FOUND': 'User not found',
    'INTERNAL_SERVER_ERROR': 'Internal server error',
    'EMAIL_NOT_FOUND': 'Email not found!',
    'INVALID_PASSWORD': 'Invalid password!',
    'OLD_PASSWORD_MISMATCH': 'Old password does not match',
    'INVALID_VERIFCATION_CODE': 'Invalid verification code',
    'USER_ALREADY_VERIFIED': 'User already verified',
    'NO_TOKEN_PROVIDED': 'No token provided',
    'TOKEN_INVALID_OR_REVOKED': 'Token not found or already revoked.',
    'SEND_RESET_PASSWORD_EMAIL_FAILED': 'Failed to send reset password email',
    'FORGOT_PASSWORD_SEND_EMAIL_ERROR': 'Error sending forgot password email',
    'OLD_NEW_PASSWORD_SAME': 'Old and new password cannot be the same',
    'CONFIRM_PASSWORD_MISMATCH': 'Confirm password does not match new password',
    'ALREADY_ON_WAITLIST': 'You are already on waitlist',
    'ADDED_TO_WAITLIST_FAILED': 'Failed to register for waitlist',
    'WAITLIST': 'Waitlist mail sending failed',
    'SURVEY_SUBMIT_FAILED': 'Failed to submit survey',
    'WAITLIST_SEND_EMAIL_ERROR': 'Failed to send waitlist thank you email.',
    'PRE_REGISTRATION_SURVEY_SEND_EMAIL_ERROR': 'Failed to send pre-registration survey email.',
    'INTERVIEW_OBJECT_NOT_FOUND': 'Interview object not found',
    'INTERVIEW_OBJECT_META_NOT_FOUND': 'Interview object meta not found',
    'INTERVIEW_INITIATION_FAILED': 'Failed to initiate interview',
    'FAILED_TO_FIND_INTERVIEWS': 'Failed to find interviews'
}